version: '3'

services:
  app:
    build: .
    volumes:
    - .:/opt/app
    command: python cli.py
    working_dir: /opt/app
    ports:
    - 8000:8000
    depends_on:
    - db
    restart: unless-stopped
  db:
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    expose:
    - '5432'
    image: postgres
    ports:
    - 127.0.0.1:5432:5432
    volumes:
    - ./db:/var/lib/postgresql
    restart: unless-stopped
